server:
  port: 8004
spring:
  profiles:
    active: rabbitmq-prod,timeline-dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


logging:
  level:
    com.own.microservice.provider.friends.circle.timeline: trace



swagger:
  enabled: true
  title: 朋友圈时间线服务提供者
  base-package: com.own.microservice.provider.friends.circle.timeline.controller


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password123@localhost:39999/eureka/
