spring:
  rabbitmq:
    username: admin
    password: 123456
    host: 192.168.11.4
    port:  5672
    #配置发布消息确认回调
    publisher-confirms: true
    #虚拟空间地址
    virtual-host: /
Testt: 测试
# 刷新配置，在spring boot 2.x 之前1.x的management.security.enabled失效，新的配置为
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh