spring:
  data:
    mongodb:
      # username: root
      # password: root
      database: communication_circle_album
      uri: mongodb://localhost:27017
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


swagger:
  enabled: true
  title: 朋友圈相册服务提供
  base-package: com.own.microservice.provide.rfriends.circle.album.controller
