spring:
  data:
    mongodb:
      # username: communication
      # password: 123456
      database: communication_circle_comment
      uri: mongodb://localhost:27017


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


logging:
  level:
    com.own.microservice.provider.friends.circle.comment: trace



swagger:
  enabled: true
  title: 朋友圈评论服务提供者
  base-package: com.own.microservice.provider.friends.circle.comment.controller