spring:
  data:
    mongodb:
#      username: communication
#      password: 123456
#      database:
      uri: mongodb://39.104.16.81:27017/communication_circle_comment

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


logging:
  level:
    com.own.microservice.provider.friends.circle.comment: trace



swagger:
  enabled: true
  title: 朋友圈评论服务提供者
  base-package: com.own.microservice.provider.friends.circle.comment.controller